-- Add translation keys for AdminDashboard.tsx and TranslationSeeder.tsx
INSERT INTO translations (key, hu, en) VALUES
-- AdminDashboard loading and navigation
('admin.dashboard.loading', 'Betöltés...', 'Loading...'),
('admin.dashboard.total_users', 'Összes felhasználó', 'Total Users'),
('admin.dashboard.total_revenue', 'Teljes Bevétel (USD)', 'Total Revenue (USD)'),
('admin.dashboard.revenue_source', 'Stripe + Booster vásárlásokból', 'From Stripe + Booster purchases'),
('admin.dashboard.welcome', 'Üdvözöllek az Admin Felületen!', 'Welcome to the Admin Panel!'),
('admin.dashboard.welcome_desc', 'Itt kezelheted a platform működését, megtekintheted a statisztikákat és a felhasználókat.', 'Here you can manage platform operations, view statistics and users.'),
('admin.dashboard.tip_label', 'Tipp:', 'Tip:'),
('admin.dashboard.tip_mobile', 'Használd a felső menüt a különböző funkciók eléréséhez.', 'Use the top menu to access different functions.'),
('admin.dashboard.tip_desktop', 'Használd a bal oldali menüt a különböző funkciók eléréséhez.', 'Use the left menu to access different functions.'),
('admin.dashboard.quick_links', 'Gyors elérési útvonalak', 'Quick Access'),
('admin.dashboard.view_users', 'Felhasználók', 'Users'),
('admin.dashboard.view_users_desc', 'Összes felhasználó megtekintése', 'View all users'),
('admin.dashboard.revenue', 'Bevételek', 'Revenue'),
('admin.dashboard.revenue_desc', 'Vásárlások és bevételi adatok', 'Purchases and revenue data'),
('admin.dashboard.advanced_analytics', 'Fejlett Analitika', 'Advanced Analytics'),
('admin.dashboard.retention_title', 'Retenciós Dashboard', 'Retention Dashboard'),
('admin.dashboard.retention_desc', 'DAU/WAU/MAU, kohorsz analízis, lemorzsolódás', 'DAU/WAU/MAU, cohort analysis, churn'),
('admin.dashboard.monetization_title', 'Monetizációs Dashboard', 'Monetization Dashboard'),
('admin.dashboard.monetization_desc', 'Bevétel, ARPU, konverzió, LTV analízis', 'Revenue, ARPU, conversion, LTV analysis'),
('admin.dashboard.performance_title', 'Teljesítmény Dashboard', 'Performance Dashboard'),
('admin.dashboard.performance_desc', 'Betöltési idők, TTFB, LCP, hibák', 'Load times, TTFB, LCP, errors'),
('admin.dashboard.engagement_title', 'Engagement Dashboard', 'Engagement Dashboard'),
('admin.dashboard.engagement_desc', 'Session-ök, felhasználói aktivitás, játék engagement', 'Sessions, user activity, game engagement'),
('admin.dashboard.user_journey_title', 'User Journey', 'User Journey'),
('admin.dashboard.user_journey_desc', 'Onboarding, vásárlási és játék tölcsérek', 'Onboarding, purchase and game funnels'),

-- AdminDashboard users tab
('admin.dashboard.all_users_count', 'Összes felhasználó ({count})', 'All Users ({count})'),
('admin.dashboard.search_placeholder', 'Keresés (ID, név, email, szerepkör, életek, érmék...)', 'Search (ID, name, email, role, lives, coins...)'),
('admin.dashboard.table_id', 'ID', 'ID'),
('admin.dashboard.table_username', 'Felhasználónév', 'Username'),
('admin.dashboard.table_email', 'Email', 'Email'),
('admin.dashboard.table_role', 'Szerepkör', 'Role'),
('admin.dashboard.table_lives', 'Életek', 'Lives'),
('admin.dashboard.table_coins', 'Érmék', 'Coins'),
('admin.dashboard.table_correct_answers', 'Helyes válaszok', 'Correct Answers'),
('admin.dashboard.table_registration', 'Regisztráció', 'Registration'),

-- AdminDashboard revenue tab
('admin.dashboard.total_revenue_tab', 'Teljes árbevétel', 'Total Revenue'),
('admin.dashboard.country', 'Ország', 'Country'),
('admin.dashboard.users_count', 'Felhasználók száma', 'User Count'),
('admin.dashboard.avg_spending', 'Átlagos költés', 'Average Spending'),
('admin.dashboard.flag', 'Zászló', 'Flag'),
('admin.dashboard.country_hungary', 'Magyarország', 'Hungary'),
('admin.dashboard.country_england', 'Anglia', 'England'),
('admin.dashboard.country_austria', 'Ausztria', 'Austria'),

-- AdminDashboard payouts tab
('admin.dashboard.prize_payouts', 'Nyeremény kifizetések', 'Prize Payouts'),

-- AdminDashboard invitations tab
('admin.dashboard.invitations_count', 'Meghívások ({count})', 'Invitations ({count})'),
('admin.dashboard.refreshing', '🔄 Frissítés...', '🔄 Refreshing...'),
('admin.dashboard.auto_sync_active', '✓ Automatikus szinkronizálás aktív (5mp)', '✓ Auto-sync active (5s)'),
('admin.dashboard.sync_friendships_manual', '🔄 Barátságok manuális szinkronizálása', '🔄 Manual friendships sync'),
('admin.dashboard.inviter', 'Meghívó', 'Inviter'),
('admin.dashboard.invited', 'Meghívott', 'Invited'),
('admin.dashboard.code', 'Kód', 'Code'),
('admin.dashboard.status', 'Státusz', 'Status'),
('admin.dashboard.created', 'Létrehozva', 'Created'),
('admin.dashboard.activated', 'Aktiválva', 'Activated'),
('admin.dashboard.not_registered_yet', 'Még nem regisztrált', 'Not registered yet'),
('admin.dashboard.accepted', '✓ Elfogadva', '✓ Accepted'),
('admin.dashboard.pending', '⏳ Függőben', '⏳ Pending'),
('admin.dashboard.no_invitations', 'Nincs meghívás', 'No invitations'),

-- AdminDashboard reports tab
('admin.dashboard.reports_count', 'Jelentések ({count})', 'Reports ({count})'),
('admin.dashboard.report_type_development', '🐛 Development ({count})', '🐛 Development ({count})'),
('admin.dashboard.report_type_support', '⚠️ Support ({count})', '⚠️ Support ({count})'),
('admin.dashboard.report_type_bug', '🐛 Fejlesztői', '🐛 Development'),
('admin.dashboard.report_type_user', '⚠️ Felhasználói', '⚠️ User Report'),
('admin.dashboard.report_status_pending', '⏳ Függőben', '⏳ Pending'),
('admin.dashboard.report_status_reviewing', '📋 Folyamatban', '📋 In Progress'),
('admin.dashboard.report_status_resolved', '✅ Megoldva', '✅ Resolved'),
('admin.dashboard.report_status_dismissed', '❌ Elutasítva', '❌ Dismissed'),
('admin.dashboard.reporter', 'Bejelentő:', 'Reporter:'),
('admin.dashboard.unknown', 'Ismeretlen', 'Unknown'),
('admin.dashboard.category', 'Kategória:', 'Category:'),
('admin.dashboard.description_label', 'Leírás:', 'Description:'),
('admin.dashboard.reported_user', 'Jelentett felhasználó:', 'Reported User:'),
('admin.dashboard.violation_type', 'Visszaélés típusa:', 'Violation Type:'),
('admin.dashboard.details', 'Részletek:', 'Details:'),
('admin.dashboard.screenshots', 'Képernyőképek:', 'Screenshots:'),
('admin.dashboard.screenshot_error', 'Hiba', 'Error'),

-- TranslationSeeder component
('translation_seeder.checking_content', 'Tartalom ellenőrzése...', 'Checking content...'),
('translation_seeder.translating', 'Fordítás folyamatban...', 'Translation in progress...'),
('translation_seeder.no_untranslated', 'Nincs fordítandó szöveg', 'No untranslated text'),
('translation_seeder.translate_ui', 'UI Szövegek fordítása', 'Translate UI Texts'),
('translation_seeder.all_translated', 'Minden UI szöveg már le van fordítva mind a 7 nyelvre', 'All UI texts are already translated to all 7 languages')
ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en;