-- Add translation keys for AdminGameProfiles, AdminGameProfileDetail, AdminLogin, EngagementDashboard, MonetizationDashboard, UserJourneyDashboard
INSERT INTO public.translations (key, hu, en) VALUES
-- AdminGameProfiles
('admin.game_profiles.title', 'Játékos Profilok', 'Game Profiles'),
('admin.game_profiles.description', 'Összes felhasználó játékstatisztikája és személyre szabási állapota', 'All user game statistics and personalization status'),
('admin.game_profiles.info_alert', 'Ez az oldal minden felhasználó összesített játékadatait mutatja. A személyre szabás akkor aktiválódik, ha a felhasználó legalább 30 kérdést megválaszolt.', 'This page shows aggregated game data for all users. Personalization activates when a user has answered at least 30 questions.'),
('admin.game_profiles.search_placeholder', 'Keresés User ID vagy username alapján...', 'Search by User ID or username...'),
('admin.game_profiles.sort.answered', 'Rendezés válaszolt kérdések szerint', 'Sort by Answered'),
('admin.game_profiles.sort.correctness', 'Rendezés helyesség szerint', 'Sort by Correctness'),
('admin.game_profiles.sort.active', 'Rendezés aktív szerint', 'Sort by Active'),
('admin.game_profiles.table.user', 'Felhasználó', 'User'),
('admin.game_profiles.table.total_answers', 'Összes Válasz', 'Total Answers'),
('admin.game_profiles.table.correctness', 'Helyesség', 'Correctness'),
('admin.game_profiles.table.likes_dislikes', 'Likes/Dislikes', 'Likes/Dislikes'),
('admin.game_profiles.table.ai_status', 'AI Státusz', 'AI Status'),
('admin.game_profiles.table.top_topics', 'Top Témák', 'Top Topics'),
('admin.game_profiles.table.actions', 'Műveletek', 'Actions'),
('admin.game_profiles.details_button', 'Részletek', 'Details'),
('admin.game_profiles.personalization_active', 'Aktív', 'Active'),
('admin.game_profiles.personalization_pending', 'Várakozás', 'Pending'),
('admin.game_profiles.personalization_inactive', 'Inaktív', 'Inactive'),
('admin.game_profiles.loading', 'Betöltés...', 'Loading...'),
('admin.game_profiles.error_loading', 'Hiba a profilok betöltése során', 'Error loading profiles'),
-- AdminGameProfileDetail
('admin.game_profile_detail.title', 'Játékos Profil Részletek', 'Game Profile Details'),
('admin.game_profile_detail.back_button', 'Vissza a profilokhoz', 'Back to Profiles'),
('admin.game_profile_detail.overview_title', 'Áttekintés', 'Overview'),
('admin.game_profile_detail.username', 'Felhasználónév', 'Username'),
('admin.game_profile_detail.user_id', 'User ID', 'User ID'),
('admin.game_profile_detail.total_answered', 'Összes válaszolt', 'Total Answered'),
('admin.game_profile_detail.correctness_rate', 'Helyességi arány', 'Correctness Rate'),
('admin.game_profile_detail.likes', 'Likeok', 'Likes'),
('admin.game_profile_detail.dislikes', 'Dislikeok', 'Dislikes'),
('admin.game_profile_detail.ai_personalization', 'AI Személyre szabás', 'AI Personalization'),
('admin.game_profile_detail.ai_active', 'Aktív', 'Active'),
('admin.game_profile_detail.ai_pending', 'Várakozás (még 30 válasz szükséges)', 'Pending (30 answers required)'),
('admin.game_profile_detail.ai_disabled', 'Kikapcsolva', 'Disabled'),
('admin.game_profile_detail.top_topics_title', 'Top Témakörök', 'Top Topics'),
('admin.game_profile_detail.no_topics', 'Még nincsenek témakör statisztikák', 'No topic statistics yet'),
('admin.game_profile_detail.topic', 'Téma', 'Topic'),
('admin.game_profile_detail.correct', 'Helyes', 'Correct'),
('admin.game_profile_detail.total', 'Összes', 'Total'),
('admin.game_profile_detail.loading', 'Betöltés...', 'Loading...'),
('admin.game_profile_detail.error_loading', 'Hiba a profil betöltése során', 'Error loading profile'),
-- AdminLogin
('admin.login.title', 'Admin Belépés', 'Admin Login'),
('admin.login.subtitle', 'Csak adminisztrátorok számára', 'For administrators only'),
('admin.login.username_label', 'Felhasználónév', 'Username'),
('admin.login.pin_label', 'PIN kód', 'PIN code'),
('admin.login.login_button', 'Bejelentkezés', 'Login'),
('admin.login.logging_in', 'Bejelentkezés...', 'Logging in...'),
('admin.login.back_to_home', 'Vissza a főoldalra', 'Back to home'),
-- EngagementDashboard
('admin.engagement.description', 'Az engagement analytics részletes betekintést nyújt a felhasználók aktivitásába, session-jeibe és funkció használatába.', 'Engagement analytics provides detailed insights into user activity, sessions, and feature usage.'),
-- MonetizationDashboard
('admin.monetization.title', 'Monetization Dashboard', 'Monetization Dashboard'),
('admin.monetization.subtitle', 'Részletes bevételi és vásárlási metrikák', 'Detailed revenue and purchase metrics'),
('admin.monetization.total_revenue', 'Összes Bevétel', 'Total Revenue'),
('admin.monetization.arpu_desc', 'Átlagos bevétel felhasználónként', 'Average revenue per user'),
('admin.monetization.arppu_desc', 'Átlagos bevétel fizető felhasználónként', 'Average revenue per paying user'),
('admin.monetization.conversion_rate', 'Konverziós Arány', 'Conversion Rate'),
('admin.monetization.revenue_over_time', 'Bevétel Időben', 'Revenue Over Time'),
('admin.monetization.revenue_by_product', 'Bevétel Termékek Szerint', 'Revenue by Product'),
('admin.monetization.no_data', 'Még nincs monetizációs adat', 'No monetization data yet'),
-- UserJourneyDashboard
('admin.journey.description', 'A User Journey Dashboard segít megérteni, hogyan navigálnak a felhasználók az alkalmazásban és hol morzsolódnak le.', 'The User Journey Dashboard helps understand how users navigate through the app and where they drop off.')
ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en,
  updated_at = NOW();