-- Add translation keys for AdminReportActionDialog, AdminQuestionPools, ProfileGame, and PerformanceDashboard
INSERT INTO public.translations (key, hu, en) VALUES
-- AdminReportActionDialog problem types
('admin.report.problem_game_crash', '🎮 Játék összeomlás / nem indul', '🎮 Game crash / won''t start'),
('admin.report.problem_question_display', '❓ Kérdés nem jelenik meg helyesen', '❓ Question not displaying correctly'),
('admin.report.problem_correct_marked_wrong', '✅ Helyes válasz helytelennek jelölve', '✅ Correct answer marked as wrong'),
('admin.report.problem_wrong_marked_correct', '❌ Helytelen válasz helyesnek jelölve', '❌ Wrong answer marked as correct'),
('admin.report.problem_timer', '⏱️ Időzítő hiba / nem működik', '⏱️ Timer error / not working'),
('admin.report.problem_coins_life_not_credited', '💰 Érme/élet nem lett jóváírva', '💰 Coins/lives not credited'),
('admin.report.problem_booster_not_activated', '🚀 Booster nem aktiválódott', '🚀 Booster not activated'),
('admin.report.problem_reward_not_received', '🎁 Ajándék/jutalom nem érkezett meg', '🎁 Gift/reward not received'),
('admin.report.problem_chat_message_cant_send', '💬 Chat üzenet nem küldhető', '💬 Chat message can''t be sent'),
('admin.report.problem_media_upload', '📸 Kép/média feltöltési hiba', '📸 Image/media upload error'),
('admin.report.problem_friend_add', '👥 Barát hozzáadási probléma', '👥 Friend add problem'),
('admin.report.problem_leaderboard_not_updating', '🏆 Ranglista nem frissül', '🏆 Leaderboard not updating'),
('admin.report.problem_payment', '💳 Fizetési hiba', '💳 Payment error'),
('admin.report.problem_login', '🔐 Bejelentkezési probléma', '🔐 Login problem'),
('admin.report.problem_mobile_display', '📱 Mobil megjelenítési hiba', '📱 Mobile display error'),
('admin.report.problem_technical_other', '🐛 Egyéb technikai hiba', '🐛 Other technical error'),
('admin.report.problem_performance', '⚡ Teljesítmény probléma / lassú', '⚡ Performance problem / slow'),
('admin.report.problem_sync', '🔄 Szinkronizálási hiba', '🔄 Synchronization error'),
-- AdminReportActionDialog dismissal reasons
('admin.report.dismiss_not_reproducible', '✅ Nem reprodukálható - nem sikerült újra előidézni', '✅ Not reproducible - couldn''t recreate'),
('admin.report.dismiss_device_specific', '📱 Eszköz specifikus - csak bizonyos eszközökön fordul elő', '📱 Device specific - only on certain devices'),
('admin.report.dismiss_browser_specific', '🌐 Böngésző specifikus - használj másik böngészőt', '🌐 Browser specific - use another browser'),
('admin.report.dismiss_already_fixed', '🔄 Már javítva - a legújabb verzióban megoldva', '🔄 Already fixed - solved in latest version'),
('admin.report.dismiss_intended_behavior', '⚙️ Helyes működés - ez így van tervezve', '⚙️ Correct behavior - this is as designed'),
('admin.report.dismiss_duplicate', '📋 Duplikált bejelentés - már jelentették', '📋 Duplicate report - already reported'),
('admin.report.dismiss_user_error', '🔧 Felhasználói hiba - nem megfelelő használat', '🔧 User error - incorrect usage'),
('admin.report.dismiss_internet_connection', '📶 Internetkapcsolat probléma - nem az app hibája', '📶 Internet connection problem - not app error'),
('admin.report.dismiss_storage', '💾 Eszköz tárhely probléma - nincs elég hely', '💾 Device storage problem - not enough space'),
('admin.report.dismiss_battery', '🔋 Alacsony akkumulátor - energiatakarékos mód aktív', '🔋 Low battery - power saving mode active'),
('admin.report.dismiss_outdated_version', '📵 Elavult verzió - frissítsd az appot', '📵 Outdated version - update the app'),
('admin.report.dismiss_permissions', '🔐 Engedélyek hiánya - add meg a szükséges jogokat', '🔐 Missing permissions - grant required permissions'),
('admin.report.dismiss_no_violation', '✅ Nem sérti a szabályokat - normális viselkedés', '✅ No violation - normal behavior'),
('admin.report.dismiss_insufficient_evidence', '📝 Nincs elegendő bizonyíték - több részlet szükséges', '📝 Insufficient evidence - more details needed'),
('admin.report.dismiss_misunderstanding', '🤝 Félreértés - nem rosszhiszemű szándék', '🤝 Misunderstanding - not malicious intent'),
('admin.report.dismiss_no_context', '💬 Kontextus hiányában nem értelmezhető', '💬 Not interpretable without context'),
('admin.report.dismiss_protected_conversation', '👤 Védett beszélgetés - nem nyilvános tartalom', '👤 Protected conversation - not public content'),
('admin.report.dismiss_out_of_scope', '⚖️ Nem tartozik az admin hatáskörbe', '⚖️ Not within admin scope'),
('admin.report.dismiss_automated_message', '🔄 Automatikus rendszerüzenet - nem felhasználótól', '🔄 Automated system message - not from user'),
('admin.report.dismiss_joke', '😊 Viccből írt üzenet - nem komoly szándék', '😊 Joke message - not serious intent'),
('admin.report.dismiss_language_difference', '🗣️ Nyelvi különbség - nem sértés, csak másképp fogalmazott', '🗣️ Language difference - not offensive, just differently worded'),
('admin.report.dismiss_mutual_agreement', '🔒 Mindkét fél jóváhagyta - privát megállapodás', '🔒 Both parties approved - private agreement'),
-- AdminReportActionDialog action config
('admin.report.action_reviewing_title', 'Jelentés folyamatban', 'Report in progress'),
('admin.report.action_reviewing_desc', 'Jelezd a felhasználónak, hogy a jelentést folyamatban van vizsgálva.', 'Let the user know the report is being reviewed.'),
('admin.report.action_reviewing_button', 'Folyamatba helyezés', 'Place in progress'),
('admin.report.action_reviewing_default_msg', 'Folyamatban van. Köszönjük a jelzésedet! A csapatunk vizsgálja az ügyet, és hamarosan válaszolunk.', 'In progress. Thank you for reporting! Our team is investigating and will respond soon.'),
('admin.report.action_resolved_title', 'Jelentés megoldva', 'Report resolved'),
('admin.report.action_resolved_desc', 'Jelezd a felhasználónak, hogy a jelentés meg lett oldva.', 'Let the user know the report has been resolved.'),
('admin.report.action_resolved_button', 'Megoldva', 'Resolved'),
('admin.report.action_resolved_default_msg', 'Köszönjük a jelentésedet! Az általad jelzett problémát megoldottuk.', 'Thank you for your report! The issue you reported has been resolved.'),
('admin.report.action_dismissed_title', 'Jelentés elutasítva', 'Report dismissed'),
('admin.report.action_dismissed_desc', 'Jelezd a felhasználónak, hogy a jelentés el lett utasítva és miért.', 'Let the user know the report has been dismissed and why.'),
('admin.report.action_dismissed_button', 'Elutasítás', 'Dismiss'),
('admin.report.action_dismissed_default_msg', 'Köszönjük a jelentésedet. Sajnos ez a jelentés nem igényel további intézkedést.', 'Thank you for your report. Unfortunately, this report does not require further action.'),
-- AdminReportActionDialog labels and messages
('admin.report.reason_label', '⚠️ Indoklás (KÖTELEZŐ) - Miért', '⚠️ Justification (REQUIRED) - Why'),
('admin.report.reason_reviewing_suffix', 'van folyamatban', 'in progress'),
('admin.report.reason_resolved_suffix', 'lett megoldva', 'was resolved'),
('admin.report.reason_dismissed_suffix', 'lett elutasítva', 'was dismissed'),
('admin.report.reason_explain', 'Magyarázd el részletesen a döntésed okát. Ez az üzenet el lesz küldve a bejelentőnek.', 'Explain your decision in detail. This message will be sent to the reporter.'),
('admin.report.placeholder_reviewing', 'Pl.: A hibát vizsgáljuk, a fejlesztői csapat 24 órán belül válaszol...', 'E.g.: We are investigating the issue, the dev team will respond within 24 hours...'),
('admin.report.placeholder_resolved', 'Pl.: A hibát javítottuk a legújabb frissítésben. Köszönjük a jelzést!', 'E.g.: We fixed the issue in the latest update. Thank you for reporting!'),
('admin.report.placeholder_dismissed', 'Pl.: Ez a bejelentés nem igényel intézkedést, mert...', 'E.g.: This report does not require action because...'),
('admin.report.char_count', 'karakter', 'characters'),
('admin.report.too_short', '(túl rövid, minimum 10 karakter)', '(too short, minimum 10 characters)'),
('admin.report.problem_type_label', '⚠️ Megoldott probléma típusa (KÖTELEZŐ)', '⚠️ Resolved problem type (REQUIRED)'),
('admin.report.dismissal_reason_label', '⚠️ Elutasítás oka (KÖTELEZŐ)', '⚠️ Dismissal reason (REQUIRED)'),
('admin.report.select_problem_desc', 'Válaszd ki, milyen típusú problémát oldottál meg, vagy adj hozzá újat.', 'Select what type of problem you resolved, or add a new one.'),
('admin.report.select_dismissal_desc', 'Válaszd ki az elutasítás okát, vagy adj hozzá újat.', 'Select the dismissal reason, or add a new one.'),
('admin.report.select_problem_placeholder', 'Válassz problématípust...', 'Select problem type...'),
('admin.report.select_dismissal_placeholder', 'Válassz elutasítási okot...', 'Select dismissal reason...'),
('admin.report.add_custom_problem', '➕ Új problématípus hozzáadása', '➕ Add new problem type'),
('admin.report.add_custom_dismissal', '➕ Új elutasítási ok hozzáadása', '➕ Add new dismissal reason'),
('admin.report.input_custom_problem', 'Írd be az új problématípust...', 'Enter new problem type...'),
('admin.report.input_custom_dismissal', 'Írd be az új elutasítási okot...', 'Enter new dismissal reason...'),
('admin.report.add_button', 'Hozzáad', 'Add'),
('admin.report.sending', 'Küldés...', 'Sending...'),
('admin.report.cancel', 'Mégse', 'Cancel'),
-- AdminQuestionPools
('admin.pools.no_pools', 'Még nincs egyetlen pool sem generálva', 'No pools generated yet'),
('admin.pools.no_pools_desc', 'Kattints a "Poolok Újragenerálása" gombra a létrehozáshoz', 'Click "Regenerate Pools" button to create'),
('admin.pools.regenerate', 'Poolok Újragenerálása', 'Regenerate Pools'),
('admin.pools.loading', 'Betöltés...', 'Loading...'),
-- ProfileGame
('profile_game.error_loading', 'Hiba történt az adatok betöltésekor', 'Error loading data'),
-- PerformanceDashboard
('performance.error_loading', 'Hiba történt az adatok betöltése során', 'Error loading data'),
('performance.errors_by_page', 'Hibák Oldalanként', 'Errors by Page'),
('performance.errors_by_page_title', 'Oldalankénti Hibák', 'Errors by Page'),
('performance.errors_by_page_desc', 'JavaScript hibák és kivételek oldalanként csoportosítva. Segít azonosítani, mely oldalakon történnek a legtöbb hibák.', 'JavaScript errors and exceptions grouped by page. Helps identify which pages have the most errors.'),
('performance.errors_by_page_interpretation', 'Magas hibaszám egy oldalon kódhiba vagy rossz felhasználói élmény jelzője. Azonnal javítandó.', 'High error count on a page indicates code bugs or poor user experience. Fix immediately.'),
('performance.error_count', 'hiba', 'errors'),
('performance.no_errors_page', 'Nincs rögzített hiba ezen az oldalon', 'No recorded errors on this page'),
('performance.top_errors', 'Top Hibák', 'Top Errors'),
('performance.top_errors_title', 'Leggyakoribb Hibák', 'Most Common Errors'),
('performance.top_errors_desc', 'A leggyakrabban előforduló hibák típusa és üzenete. Ezek prioritást kapnak a hibajavításban.', 'Type and message of most common errors. These get priority in bug fixing.'),
('performance.top_errors_interpretation', 'A leggyakoribb hibák javítása a legnagyobb hatással lesz a felhasználói élményre.', 'Fixing the most common errors will have the biggest impact on user experience.'),
('performance.no_errors', 'Nincs rögzített hiba', 'No recorded errors')
ON CONFLICT (key) DO UPDATE SET hu = EXCLUDED.hu, en = EXCLUDED.en;