-- Add missing translation keys for PerformanceDashboard
INSERT INTO translations (key, hu, en) VALUES
  ('admin.performance.avg_load_time', 'Átlagos Betöltési Idő', 'Average Load Time'),
  ('admin.performance.load_time_title', 'Betöltési Idő (Load Time)', 'Load Time'),
  ('admin.performance.load_time_desc', 'Az oldal teljes betöltési ideje milliszekundumban, a DNS keresésétől kezdve a teljes megjelenésig.', 'Total page load time in milliseconds, from DNS lookup to complete rendering.'),
  ('admin.performance.load_time_interpretation', 'Jó: <2000ms | Közepes: 2000-4000ms | Lassú: >4000ms', 'Good: <2000ms | Medium: 2000-4000ms | Slow: >4000ms'),
  ('admin.performance.avg_ttfb', 'Átlagos TTFB', 'Average TTFB'),
  ('admin.performance.ttfb_title', 'Time To First Byte', 'Time To First Byte'),
  ('admin.performance.ttfb_desc', 'Az első bájt megérkezésének ideje a szerverről. Azt mutatja, mennyire gyorsan válaszol a backend.', 'Time for the first byte to arrive from the server. Shows how quickly the backend responds.'),
  ('admin.performance.ttfb_interpretation', 'Jó: <200ms | Közepes: 200-500ms | Lassú: >500ms', 'Good: <200ms | Medium: 200-500ms | Slow: >500ms'),
  ('admin.performance.avg_lcp', 'Átlagos LCP', 'Average LCP'),
  ('admin.performance.lcp_title', 'Largest Contentful Paint', 'Largest Contentful Paint'),
  ('admin.performance.lcp_desc', 'A legnagyobb tartalmi elem megjelenési ideje. Google Core Web Vitals egyik fő metrikája.', 'Display time of the largest content element. One of Google''s Core Web Vitals.'),
  ('admin.performance.lcp_interpretation', 'Jó: <2.5s | Közepes: 2.5-4s | Lassú: >4s', 'Good: <2.5s | Medium: 2.5-4s | Slow: >4s'),
  ('admin.performance.avg_cls', 'Átlagos CLS', 'Average CLS'),
  ('admin.performance.cls_title', 'Cumulative Layout Shift', 'Cumulative Layout Shift'),
  ('admin.performance.cls_desc', 'A vizuális stabilitás mérőszáma. Azt mutatja, mennyire ''ugrál'' az oldal betöltés közben.', 'Visual stability metric. Shows how much the page ''jumps'' during loading.'),
  ('admin.performance.cls_interpretation', 'Jó: <0.1 | Közepes: 0.1-0.25 | Lassú: >0.25', 'Good: <0.1 | Medium: 0.1-0.25 | Slow: >0.25'),
  ('admin.performance.by_page_title', 'Teljesítmény Oldalanként', 'Performance by Page'),
  ('admin.performance.by_page_metric_title', 'Oldalankénti Teljesítmény', 'Performance by Page'),
  ('admin.performance.by_page_desc', 'Minden egyes oldal átlagos betöltési ideje. Ez segít azonosítani, mely oldalak lassúak és optimalizálásra szorulnak.', 'Average load time for each page. Helps identify which pages are slow and need optimization.'),
  ('admin.performance.by_page_interpretation', 'Összehasonlítsd az oldalakat egymással - a leglassabb oldalak prioritást kaphatnak az optimalizálásban.', 'Compare pages with each other - the slowest pages should be prioritized for optimization.'),
  ('admin.performance.avg_load_time_ms', 'Átlagos betöltési idő (ms)', 'Average load time (ms)'),
  ('admin.performance.by_device_title', 'Teljesítmény Eszközönként', 'Performance by Device'),
  ('admin.performance.by_device_metric_title', 'Eszközönkénti Teljesítmény', 'Performance by Device'),
  ('admin.performance.by_device_desc', 'Betöltési idők mobilon, tableten és deszktopon. A mobil felhasználók gyakran lassabb hálózatot használnak, ezért fontosak ezek a mérések.', 'Load times on mobile, tablet, and desktop. Mobile users often use slower networks, so these metrics are important.'),
  ('admin.performance.by_device_interpretation', 'Mobil optimalizálás kulcsfontosságú - a felhasználók 70-80%-a mobilról látogat.', 'Mobile optimization is crucial - 70-80% of users visit from mobile.'),
  ('admin.performance.by_browser_title', 'Teljesítmény Böngészőnként', 'Performance by Browser'),
  ('admin.performance.by_browser_metric_title', 'Böngészőnkénti Teljesítmény', 'Performance by Browser'),
  ('admin.performance.by_browser_desc', 'Betöltési idők különböző böngészőkben (Chrome, Safari, Firefox, stb.). Segít azonosítani böngésző-specifikus problémákat.', 'Load times in different browsers (Chrome, Safari, Firefox, etc.). Helps identify browser-specific issues.'),
  ('admin.performance.by_browser_interpretation', 'Ha egy böngészőben jelentősen lassabb az oldal, akkor böngésző-kompatibilitási probléma lehet.', 'If the page is significantly slower in one browser, there may be a browser compatibility issue.')
ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en;