-- Add missing translation keys for Retention Dashboard
INSERT INTO public.translations (key, hu, en) VALUES
('admin.retention.title', 'Megtartási Analitika', 'Retention Analytics'),
('admin.retention.tab_overview', 'Áttekintés', 'Overview'),
('admin.retention.tab_cohorts', 'Kohorszok', 'Cohorts'),
('admin.retention.tab_churn', 'Lemorzsolódás', 'Churn'),
('admin.retention.daily_active', 'Napi Aktív Felhasználók', 'Daily Active Users'),
('admin.retention.weekly_active', 'Heti Aktív Felhasználók', 'Weekly Active Users'),
('admin.retention.monthly_active', 'Havi Aktív Felhasználók', 'Monthly Active Users'),
('admin.retention.retention_rates', 'Megtartási Ráták', 'Retention Rates'),
('admin.retention.day_1', '1. Nap', 'Day 1'),
('admin.retention.day_7', '7. Nap', 'Day 7'),
('admin.retention.day_30', '30. Nap', 'Day 30'),
('admin.retention.cohort_analysis', 'Kohorsz Elemzés', 'Cohort Analysis'),
('admin.retention.inactive_users', 'Inaktív Felhasználók', 'Inactive Users'),
('admin.retention.days_inactive_label', 'napja inaktív', 'days inactive'),

-- Add missing translation keys for Monetization Dashboard
('admin.monetization.title', 'Monetizációs Analitika', 'Monetization Analytics'),
('admin.monetization.subtitle', 'Bevételi mutatók és konverziós adatok', 'Revenue metrics and conversion data'),
('admin.monetization.total_revenue', 'Teljes Bevétel', 'Total Revenue'),
('admin.monetization.arpu_desc', 'Átlagos bevétel felhasználónként', 'Average revenue per user'),
('admin.monetization.arppu_desc', 'Átlagos bevétel fizető felhasználónként', 'Average revenue per paying user'),
('admin.monetization.conversion_rate', 'Konverziós Ráta', 'Conversion Rate'),
('admin.monetization.paying_users', 'fizető felhasználó', 'paying users'),
('admin.monetization.revenue_over_time', 'Bevétel Időbeli Alakulása', 'Revenue Over Time'),
('admin.monetization.revenue_chart', 'Bevétel', 'Revenue'),
('admin.monetization.revenue_by_product', 'Bevétel Termék Szerint', 'Revenue by Product'),
('admin.monetization.purchase_count', 'Vásárlások Száma', 'Purchase Count'),
('admin.monetization.no_data', 'Nincs elérhető adat', 'No data available'),

-- Add missing translation keys for Performance Dashboard
('admin.performance.dashboard_title', 'Teljesítmény Dashboard', 'Performance Dashboard'),
('admin.performance.dashboard_subtitle', 'Alkalmazás teljesítménye és hibák', 'Application performance and errors'),
('admin.performance.refresh_button', 'Frissítés', 'Refresh'),
('admin.performance.tab_overview', 'Áttekintés', 'Overview'),
('admin.performance.tab_pages', 'Oldalak', 'Pages'),
('admin.performance.tab_devices', 'Eszközök', 'Devices'),
('admin.performance.tab_errors', 'Hibák', 'Errors'),
('admin.performance.avg_load_time', 'Átlagos Betöltési Idő', 'Average Load Time'),
('admin.performance.load_time_title', 'Betöltési Idő', 'Load Time'),
('admin.performance.load_time_desc', 'Az oldal betöltéséhez szükséges átlagos idő', 'Average time required to load the page'),
('admin.performance.load_time_interpretation', 'Alacsonyabb értékek jobb felhasználói élményt jelentenek', 'Lower values mean better user experience'),
('admin.performance.avg_ttfb', 'Átlagos TTFB', 'Average TTFB'),
('admin.performance.ttfb_title', 'Time To First Byte', 'Time To First Byte'),
('admin.performance.ttfb_desc', 'Első bájt megérkezéséig eltelt idő', 'Time until first byte arrives'),
('admin.performance.ttfb_interpretation', 'A szerver válaszidejének mérőszáma', 'Measure of server response time'),
('admin.performance.avg_lcp', 'Átlagos LCP', 'Average LCP'),
('admin.performance.lcp_title', 'Largest Contentful Paint', 'Largest Contentful Paint'),
('admin.performance.lcp_desc', 'A legnagyobb tartalom megjelenési ideje', 'Time until largest content appears'),
('admin.performance.lcp_interpretation', 'Ideális érték: 2.5 másodperc alatt', 'Ideal value: under 2.5 seconds'),
('admin.performance.avg_cls', 'Átlagos CLS', 'Average CLS'),
('admin.performance.cls_title', 'Cumulative Layout Shift', 'Cumulative Layout Shift'),
('admin.performance.cls_desc', 'Az oldal vizuális stabilitásának mérőszáma', 'Measure of page visual stability'),
('admin.performance.cls_interpretation', 'Alacsonyabb értékek stabilabb elrendezést jelentenek', 'Lower values mean more stable layout'),
('admin.performance.by_page_title', 'Teljesítmény Oldalanként', 'Performance by Page'),
('admin.performance.by_page_metric_title', 'Oldalankénti Teljesítmény', 'Page-wise Performance'),
('admin.performance.by_page_desc', 'Átlagos betöltési idő minden oldalon', 'Average load time per page'),
('admin.performance.by_page_interpretation', 'Azonosítja a lassú oldalakat', 'Identifies slow pages'),
('admin.performance.avg_load_time_ms', 'Átlagos Betöltési Idő (ms)', 'Average Load Time (ms)'),
('admin.performance.by_device_title', 'Teljesítmény Eszköz Szerint', 'Performance by Device'),
('admin.performance.by_device_metric_title', 'Eszközönkénti Teljesítmény', 'Device-wise Performance'),
('admin.performance.by_device_desc', 'Átlagos betöltési idő eszköztípusonként', 'Average load time per device type'),
('admin.performance.by_device_interpretation', 'Mobil vs. asztali teljesítmény összehasonlítása', 'Compare mobile vs. desktop performance'),
('admin.performance.by_browser_title', 'Teljesítmény Böngésző Szerint', 'Performance by Browser'),
('admin.performance.by_browser_metric_title', 'Böngészőnkénti Teljesítmény', 'Browser-wise Performance'),
('admin.performance.by_browser_desc', 'Átlagos betöltési idő böngészőnként', 'Average load time per browser'),
('admin.performance.by_browser_interpretation', 'Böngésző-specifikus problémák azonosítása', 'Identify browser-specific issues'),
('performance.error_loading', 'Hiba történt az adatok betöltésekor', 'Error loading data'),
('performance.errors_by_page', 'Hibák Oldalanként', 'Errors by Page'),
('performance.errors_by_page_title', 'Hibák Oldalanként', 'Errors by Page'),
('performance.errors_by_page_desc', 'Hibák száma minden oldalon', 'Number of errors per page'),
('performance.errors_by_page_interpretation', 'Azonosítja a problémás oldalakat', 'Identifies problematic pages'),
('performance.error_count', 'hiba', 'errors'),
('performance.no_errors_page', 'Nincsenek hibák', 'No errors'),
('performance.top_errors', 'Legtöbb Hiba', 'Top Errors'),
('performance.top_errors_title', 'Leggyakoribb Hibák', 'Most Common Errors'),
('performance.top_errors_desc', 'A leggyakrabban előforduló hibák', 'Most frequently occurring errors'),
('performance.top_errors_interpretation', 'Priorizálja a hibajavításokat', 'Prioritize bug fixes'),
('performance.no_errors', 'Nincsenek rögzített hibák', 'No errors recorded'),

-- Add missing translation keys for User Journey Dashboard
('admin.journey.title', 'Felhasználói Út Analitika', 'User Journey Analytics'),
('admin.journey.description', 'Követje nyomon a felhasználók útját az alkalmazáson keresztül, és azonosítsa a konverziós akadályokat és optimalizálási lehetőségeket.', 'Track user paths through the application and identify conversion blockers and optimization opportunities.'),
('admin.journey.tab_onboarding', 'Onboarding', 'Onboarding'),
('admin.journey.tab_purchase', 'Vásárlás', 'Purchase'),
('admin.journey.tab_game', 'Játék', 'Game'),
('admin.journey.tab_paths', 'Útvonalak', 'Paths'),
('admin.journey.tab_exits', 'Kilépések', 'Exits'),
('admin.journey.onboarding_funnel', 'Onboarding Tölcsér', 'Onboarding Funnel'),
('admin.journey.onboarding_funnel_desc', 'Felhasználók száma minden onboarding lépésnél', 'Number of users at each onboarding step'),
('admin.journey.onboarding_funnel_interpretation', 'Azonosítja, hol adják fel a felhasználók a regisztrációt', 'Identifies where users abandon registration'),
('admin.journey.users', 'Felhasználók', 'Users'),
('admin.journey.user', 'felhasználó', 'users'),
('admin.journey.dropoff', 'lemorzsolódás', 'dropoff'),
('admin.journey.purchase_funnel', 'Vásárlási Tölcsér', 'Purchase Funnel'),
('admin.journey.purchase_funnel_desc', 'Felhasználók száma minden vásárlási lépésnél', 'Number of users at each purchase step'),
('admin.journey.purchase_funnel_interpretation', 'Mutatja a vásárlási konverziót', 'Shows purchase conversion'),
('admin.journey.game_funnel', 'Játék Tölcsér', 'Game Funnel'),
('admin.journey.game_funnel_desc', 'Felhasználók száma minden játék lépésnél', 'Number of users at each game step'),
('admin.journey.game_funnel_interpretation', 'Azonosítja, hol adják fel a felhasználók a játékot', 'Identifies where users abandon the game'),
('admin.journey.common_paths', 'Gyakori Útvonalak', 'Common Paths'),
('admin.journey.common_paths_desc', 'A leggyakoribb navigációs útvonalak', 'Most common navigation paths'),
('admin.journey.common_paths_interpretation', 'Megmutatja a tipikus felhasználói viselkedést', 'Shows typical user behavior'),
('admin.journey.occurrences', 'előfordulás', 'occurrences'),
('admin.journey.exit_points', 'Kilépési Pontok', 'Exit Points'),
('admin.journey.exit_points_desc', 'Oldalak, ahol a felhasználók kilépnek', 'Pages where users exit'),
('admin.journey.exit_points_interpretation', 'Azonosítja a lemorzsolódási pontokat', 'Identifies churn points'),
('admin.journey.exits', 'Kilépések', 'Exits')

ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en,
  updated_at = NOW();