-- Add missing translation keys for admin pages (AdminBoosterPurchases, AdminTranslations, AdminAdInterests, AdminGameProfileDetail)

INSERT INTO translations (key, hu, en) VALUES
-- AdminBoosterPurchases
('admin.booster_purchases.title', 'Booster Vásárlások', 'Booster Purchases'),
('admin.booster_purchases.purchases_count', 'vásárlás', 'purchases'),
('admin.booster_purchases.free_booster', 'Free Booster', 'Free Booster'),
('admin.booster_purchases.purchased_with_gold', 'aranyért vásárolva', 'purchased with gold'),
('admin.booster_purchases.premium_booster', 'Premium Booster', 'Premium Booster'),
('admin.booster_purchases.iap_purchase', 'IAP vásárlás', 'IAP purchase'),
('admin.booster_purchases.gold_saver_booster', 'Gold Saver Booster', 'Gold Saver Booster'),
('admin.booster_purchases.during_game', 'játék közben', 'during game'),
('admin.booster_purchases.instant_rescue', 'Instant Rescue', 'Instant Rescue'),
('admin.booster_purchases.rescue_with_iap', 'mentés IAP-pal', 'rescue with IAP'),
('admin.booster_purchases.gold_spent', 'Arany kiadás', 'Gold Spent'),
('admin.booster_purchases.total', 'összesen', 'total'),
('admin.booster_purchases.usd_revenue', 'USD bevétel', 'USD Revenue'),
('admin.booster_purchases.from_iap', 'IAP-ből', 'from IAP'),
('admin.booster_purchases.search_placeholder', 'Keresés felhasználónév alapján...', 'Search by username...'),
('admin.booster_purchases.filter_source', 'Forrás szűrése', 'Filter Source'),
('admin.booster_purchases.all_sources', 'Minden forrás', 'All Sources'),
('admin.booster_purchases.gold', 'Arany', 'Gold'),
('admin.booster_purchases.iap', 'IAP', 'IAP'),
('admin.booster_purchases.filter_booster', 'Booster szűrése', 'Filter Booster'),
('admin.booster_purchases.all_boosters', 'Minden booster', 'All Boosters'),
('admin.booster_purchases.gold_saver', 'Gold Saver', 'Gold Saver'),
('admin.booster_purchases.table.user', 'Felhasználó', 'User'),
('admin.booster_purchases.table.booster', 'Booster', 'Booster'),
('admin.booster_purchases.table.source', 'Forrás', 'Source'),
('admin.booster_purchases.table.context', 'Context', 'Context'),
('admin.booster_purchases.table.gold', 'Arany', 'Gold'),
('admin.booster_purchases.table.usd', 'USD', 'USD'),
('admin.booster_purchases.table.date', 'Dátum', 'Date'),

-- AdminTranslations
('admin.translations.title', 'Fordítások kezelése', 'Manage Translations'),
('admin.translations.description', 'UI szövegek és játékkérdések fordítása 8 nyelvre', 'Translate UI texts and game questions to 8 languages'),
('admin.translations.ui_translations', 'UI Fordítások', 'UI Translations'),
('admin.translations.question_translations', 'Kérdés Fordítások', 'Question Translations'),

-- AdminAdInterests
('admin.ad_interests.title', 'Reklámprofilok (Előkészítés)', 'Ad Profiles (Preparation)'),
('admin.ad_interests.description', 'Játékadatokból származó reklám-érdeklődési analitika', 'Ad interest analytics from game data'),
('admin.ad_interests.recalculating', 'Frissítés...', 'Recalculating...'),
('admin.ad_interests.recalculate_button', 'Újraszámítás', 'Recalculate'),
('admin.ad_interests.legal_info', 'Ez a nézet a játékosok tematikus érdeklődését mutatja reklám-szempontú előkészítésként. A jelenlegi rendszerben ezek az adatok kizárólag analitikai és termékfejlesztési célokat szolgálnak, nem használjuk őket aktív reklámcélú profilozásra, és nem jelenítünk meg személyre szabott hirdetéseket. A tényleges reklám-targetálás csak akkor indul el, ha a szolgáltatás elérhetővé válik és a felhasználó ehhez kifejezetten hozzájárul.', 'This view shows player thematic interests for ad preparation purposes. In the current system, this data is used exclusively for analytical and product development purposes, we do not use it for active ad profiling, and we do not display personalized advertisements. Actual ad targeting will only start if the service becomes available and the user explicitly consents.'),
('admin.ad_interests.topics_title', 'Témakörök reklámérdeklődése', 'Topics Ad Interest'),
('admin.ad_interests.no_data', 'Nincs adat. Futtasd az újraszámítást!', 'No data. Run recalculation!'),
('admin.ad_interests.top_10_topics', 'Top 10 témakör interest score alapján', 'Top 10 topics by interest score'),
('admin.ad_interests.table.topic', 'Témakör', 'Topic'),
('admin.ad_interests.table.avg_score', 'Átlagos Interest Score', 'Average Interest Score'),
('admin.ad_interests.table.percentage', '%-ban', 'In %'),
('admin.ad_interests.table.user_count', 'User Count', 'User Count'),
('admin.ad_interests.user_level_title', 'User-szintű érdeklődés (anonim)', 'User-Level Interest (Anonymous)'),
('admin.ad_interests.filter_by_topic', 'Szűrés témakör szerint:', 'Filter by topic:'),
('admin.ad_interests.all_topics', 'Összes témakör', 'All Topics'),
('admin.ad_interests.all_topics_count', 'Összes témakör (27)', 'All Topics (27)'),
('admin.ad_interests.no_data_for_filter', 'Nincs adat a kiválasztott szűrővel.', 'No data for selected filter.'),
('admin.ad_interests.table.user_id', 'User ID (hash)', 'User ID (hash)'),
('admin.ad_interests.table.top_topics', 'Top témakörök', 'Top Topics'),
('admin.ad_interests.table.total_interests', 'Összes érdeklődés', 'Total Interests'),
('admin.pagination.previous', 'Előző', 'Previous'),
('admin.pagination.next', 'Következő', 'Next'),

-- AdminGameProfileDetail
('admin.game_profile.detailed_data', 'Részletes játékprofil adatok', 'Detailed Game Profile Data'),
('admin.game_profile.personalization_active', 'Személyre szabás aktív:', 'Personalization Active:'),
('admin.game_profile.distribution_in_use', '70/20/10 kérdéselosztás használatban', '70/20/10 question distribution in use'),
('admin.game_profile.ai_disabled', 'AI kikapcsolva:', 'AI Disabled:'),
('admin.game_profile.user_disabled', 'User kikapcsolta a személyre szabást', 'User disabled personalization'),
('admin.game_profile.learning_phase', 'Tanulási fázis:', 'Learning Phase:'),
('admin.game_profile.questions_answered', 'kérdés megválaszolva', 'questions answered'),
('admin.game_profile.total_answers', 'Összes válasz', 'Total Answers'),
('admin.game_profile.correct_answers', 'Helyes válaszok', 'Correct Answers'),
('admin.game_profile.correct_ratio', 'Helyességi arány', 'Correct Ratio'),
('admin.game_profile.likes', 'Likes', 'Likes'),
('admin.game_profile.dislikes', 'Dislikes', 'Dislikes'),
('admin.game_profile.metadata', 'Profil Metadata', 'Profile Metadata'),
('admin.game_profile.user_id', 'User ID', 'User ID'),
('admin.game_profile.registration', 'Regisztráció', 'Registration'),
('admin.game_profile.last_activity', 'Utolsó aktivitás', 'Last Activity'),
('admin.game_profile.no_data', 'Nincs adat', 'No Data'),
('admin.game_profile.top_3_topics', 'TOP 3 Témakörök', 'TOP 3 Topics'),
('admin.game_profile.highest_score_topics', 'Legnagyobb pontszámú témák', 'Highest Score Topics'),
('admin.game_profile.answer', 'válasz', 'answer'),
('admin.game_profile.correct', 'helyes', 'correct'),
('admin.game_profile.score', 'Score:', 'Score:'),
('admin.game_profile.question_distribution', 'Kérdéselosztás (70/20/10)', 'Question Distribution (70/20/10)'),
('admin.game_profile.active_personalized', 'Aktív személyre szabott elosztás', 'Active Personalized Distribution'),
('admin.game_profile.if_enabled', 'Elosztás ha be lenne kapcsolva', 'Distribution if Enabled'),
('admin.game_profile.favorite_topics', 'Kedvenc témák (TOP3)', 'Favorite Topics (TOP3)'),
('admin.game_profile.new_questions', 'Új kérdések', 'New Questions'),
('admin.game_profile.dislike_topics', 'Dislike témák', 'Dislike Topics'),
('admin.game_profile.all_topics', 'Összes Témakör', 'All Topics'),
('admin.game_profile.full_stats_by_topic', 'Teljes statisztika témánként', 'Full Statistics by Topic')

ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en;