-- Add missing translation keys for Engagement Dashboard
INSERT INTO public.translations (key, hu, en) VALUES
('admin.engagement.title', 'Elköteleződési Analitika', 'Engagement Analytics'),
('admin.engagement.description', 'Követje nyomon a felhasználói elköteleződést, funkcióhasználatot és játék aktivitást az alkalmazásban.', 'Track user engagement, feature usage, and game activity across the application.'),
('admin.engagement.tab_overview', 'Áttekintés', 'Overview'),
('admin.engagement.tab_features', 'Funkciók', 'Features'),
('admin.engagement.tab_users', 'Felhasználók', 'Users'),
('admin.engagement.tab_game', 'Játék', 'Game'),
('admin.engagement.avg_session_duration', 'Átlagos Munkamenet Időtartam', 'Average Session Duration'),
('admin.engagement.avg_session_duration_desc', 'Átlagos idő, amit a felhasználók egy munkamenetben töltenek', 'Average time users spend in a session'),
('admin.engagement.avg_session_duration_interpretation', 'Hosszabb munkamenetek magasabb elköteleződést jeleznek', 'Longer sessions indicate higher engagement'),
('admin.engagement.avg_sessions_per_user', 'Átlagos Munkamenet Felhasználónként', 'Average Sessions per User'),
('admin.engagement.avg_sessions_per_user_desc', 'Hány munkamenetet indít átlagosan egy felhasználó', 'How many sessions a user starts on average'),
('admin.engagement.avg_sessions_per_user_interpretation', 'Több munkamenet azt jelzi, hogy a felhasználók visszatérnek', 'More sessions indicate users are returning'),
('admin.engagement.total_sessions', 'Összes Munkamenet', 'Total Sessions'),
('admin.engagement.total_sessions_desc', 'Az összes rögzített munkamenet száma', 'Total number of recorded sessions'),
('admin.engagement.total_sessions_interpretation', 'Mutatja az alkalmazás teljes használatát', 'Shows overall app usage'),
('admin.engagement.engagement_by_time', 'Elköteleződés Óránként', 'Engagement by Time'),
('admin.engagement.engagement_by_time_desc', 'Munkamenetek száma napszakonként', 'Number of sessions by time of day'),
('admin.engagement.engagement_by_time_interpretation', 'Azonosítja a csúcshasználati időket', 'Identifies peak usage times'),
('admin.engagement.sessions', 'Munkamenetek', 'Sessions'),
('admin.engagement.feature_usage', 'Funkcióhasználat', 'Feature Usage'),
('admin.engagement.feature_usage_desc', 'Milyen gyakran használják az egyes funkciókat', 'How often each feature is used'),
('admin.engagement.feature_usage_interpretation', 'Azonosítja a legnépszerűbb funkciókat', 'Identifies most popular features'),
('admin.engagement.usage_count', 'Használatok Száma', 'Usage Count'),
('admin.engagement.most_active_users', 'Legaktívabb Felhasználók', 'Most Active Users'),
('admin.engagement.most_active_users_desc', 'Felhasználók a legtöbb munkamenettel', 'Users with the most sessions'),
('admin.engagement.most_active_users_interpretation', 'Azonosítja a legelkötelezettebb felhasználókat', 'Identifies most engaged users'),
('admin.engagement.session', 'munkamenet', 'sessions'),
('admin.engagement.minutes_total', ' perc összesen', ' minutes total'),
('admin.engagement.avg_games_per_user', 'Átlagos Játék Felhasználónként', 'Average Games per User'),
('admin.engagement.avg_games_per_user_desc', 'Hány játékot játszik átlagosan egy felhasználó', 'How many games a user plays on average'),
('admin.engagement.avg_games_per_user_interpretation', 'Több játék magasabb elköteleződést jelez', 'More games indicate higher engagement'),
('admin.engagement.avg_correct_answers', 'Átlagos Helyes Válaszok', 'Average Correct Answers'),
('admin.engagement.avg_correct_answers_desc', 'Átlagos helyes válaszok száma játékonként', 'Average number of correct answers per game'),
('admin.engagement.avg_correct_answers_interpretation', 'Mutatja a játékosok tudásszintjét', 'Shows player skill level'),
('admin.engagement.most_popular_topics', 'Legnépszerűbb Témakörök', 'Most Popular Topics'),
('admin.engagement.most_popular_topics_desc', 'Legtöbbet játszott témakörök', 'Most played topics'),
('admin.engagement.most_popular_topics_interpretation', 'Azonosítja a népszerű tartalmat', 'Identifies popular content'),
('admin.engagement.top_topic_score', 'Pontszám', 'Score')

ON CONFLICT (key) DO UPDATE SET
  hu = EXCLUDED.hu,
  en = EXCLUDED.en,
  updated_at = NOW();